# Generated by Django 3.2.16 on 2022-12-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tse_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('party', models.CharField(max_length=20, null=True)),
                ('electoral_unit', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
